[project]
authors = ["Mauro Silberberg <maurosilber@gmail.com>"]
channels = ["conda-forge"]
name = "marimo-web"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
edit = "marimo edit app.py"
app = "marimo run app.py"

[tasks.build-web-app]
cmd = "marimo export html-wasm app.py --output .pixi/html --mode run --no-show-code"
inputs = ["app.py"]
outputs = [".pixi/html"]

[tasks.web-app]
cwd = ".pixi/html"
cmd = "echo Open http://127.0.0.1:8000; python -m http.server"
depends-on = ["build-web-app"]

[dependencies]
altair = "*"
pandas = "*"
marimo = ">=0.10.3"
